#!/usr/bin/env python3
"""Turn results/raw/*.json into committed CSV + Markdown tables and figures.

  report.py            regenerate everything in results/tables/ and paper/figures/

Every number is read straight from a raw JSON run-unit, so the tables are a
faithful projection of the committed evidence. Emulated (Wine/DOSBox) rows are
flagged; their timings are excluded from timing tables and drawn hollow on the
Pareto charts.
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib import corpus, registry  # noqa: E402

REPO = registry.REPO_DIR
RAW = REPO / "results" / "raw"
TABLES = REPO / "results" / "tables"
FIGS = REPO / "paper" / "figures"

DATASET_LABEL = {
    "text": "Text", "documents": "Documents", "images": "Images",
    "video": "Video", "full": "Full corpus",
}


def load_all() -> list[dict]:
    rows = []
    for path in sorted(RAW.rglob("*.json")):
        try:
            rows.append(json.loads(path.read_text()))
        except json.JSONDecodeError:
            continue
    return rows


def human_bytes(n) -> str:
    if n is None:
        return "-"
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.2f} {unit}"
        n /= 1024


def fmt_secs(s) -> str:
    if s is None:
        return "-"
    if s < 10:
        return f"{s:.2f}"
    if s < 600:
        return f"{s:.1f}"
    return f"{s/60:.1f}m"


def ok_rows(rows):
    return [r for r in rows if r["status"] == "ok"]


# ---------------------------------------------------------------- CSV export
def write_csv(rows: list[dict]) -> None:
    TABLES.mkdir(parents=True, exist_ok=True)
    cols = ["id", "name", "tier", "engine", "emulated", "dataset", "level",
            "status", "input_bytes", "archive_bytes", "ratio_pct",
            "compress_s_median", "decompress_s_median",
            "compress_rss_bytes", "verify"]
    with open(TABLES / "results.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(cols)
        for r in sorted(rows, key=lambda r: (r["dataset"], r["id"], r["level"])):
            w.writerow([
                r["id"], r["name"], r["tier"], r["engine"], r["emulated"],
                r["dataset"], r["level"], r["status"], r["input_bytes"],
                r.get("archive_bytes"), r.get("ratio_pct"),
                r.get("compress_s_median"), r.get("decompress_s_median"),
                r.get("compress_rss_bytes"),
                (r.get("verify") or {}).get("detail", ""),
            ])


# ---------------------------------------------------------------- per-dataset ranking tables
def dataset_table(rows: list[dict], dataset: str) -> str:
    sub = [r for r in ok_rows(rows) if r["dataset"] == dataset]
    if not sub:
        return ""
    sub.sort(key=lambda r: r["ratio_pct"])
    input_b = sub[0]["input_bytes"]
    lines = [
        f"### {DATASET_LABEL[dataset]} ({human_bytes(input_b)})",
        "",
        "| Rank | Format | Level | Size | Ratio | Compress | Decompress | Notes |",
        "|---:|---|---|---:|---:|---:|---:|---|",
    ]
    for i, r in enumerate(sub, 1):
        emu = " ⚙" if r["emulated"] else ""
        ctime = "—" if r["emulated"] else fmt_secs(r.get("compress_s_median"))
        dtime = "—" if r["emulated"] else fmt_secs(r.get("decompress_s_median"))
        note = "emulated (size only)" if r["emulated"] else ""
        lines.append(
            f"| {i} | {r['name']}{emu} | {r['level']} | "
            f"{human_bytes(r['archive_bytes'])} | {r['ratio_pct']:.2f}% | "
            f"{ctime} | {dtime} | {note} |")
    lines.append("")
    return "\n".join(lines)


def attempted_table(rows: list[dict]) -> str:
    bad = [r for r in rows if r["status"] != "ok"]
    if not bad:
        return ""
    seen, uniq = set(), []
    for r in bad:
        key = (r["id"], r["level"], r["dataset"])
        if key in seen:
            continue
        seen.add(key)
        uniq.append(r)
    lines = [
        "### Attempted but not completed",
        "",
        "| Format | Level | Dataset | Outcome | Reason |",
        "|---|---|---|---|---|",
    ]
    for r in sorted(uniq, key=lambda r: (r["id"], r["dataset"], r["level"])):
        reason = (r.get("error") or "").split("\n")[0][:80]
        lines.append(f"| {r['name']} | {r['level']} | {r['dataset']} | "
                     f"{r['status']} | {reason} |")
    lines.append("")
    return "\n".join(lines)


def write_markdown(rows: list[dict]) -> None:
    parts = [
        "# Results",
        "",
        "Generated by `harness/report.py` from the committed raw run-units in "
        "`results/raw/`. Ratio = archive size ÷ input size (lower is better). "
        "Rows marked ⚙ ran under emulation (Wine/DOSBox); their **sizes** are "
        "comparable but their **timings are excluded** (shown as —).",
        "",
        "## Rankings by content type",
        "",
    ]
    for ds in corpus.DATASETS:
        t = dataset_table(rows, ds)
        if t:
            parts.append(t)
    parts.append("## " + "Attempted formats")
    parts.append("")
    at = attempted_table(rows)
    parts.append(at if at else "_All queued run-units completed successfully._")
    (TABLES / "results.md").write_text("\n".join(parts))


# ---------------------------------------------------------------- Pareto figures
def write_figures(rows: list[dict]) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available - skipping figures")
        return
    FIGS.mkdir(parents=True, exist_ok=True)

    for ds in ("full", "text"):
        sub = [r for r in ok_rows(rows)
               if r["dataset"] == ds and not r["emulated"]
               and r.get("compress_s_median")]
        if not sub:
            continue
        fig, ax = plt.subplots(figsize=(8, 5.5))
        for r in sub:
            x = max(r["compress_s_median"], 0.01)
            y = r["ratio_pct"]
            ax.scatter(x, y, s=28, color="#4C72B0", zorder=3)
            ax.annotate(r["id"], (x, y), fontsize=6.5,
                        xytext=(3, 2), textcoords="offset points")
        ax.set_xscale("log")
        ax.set_xlabel("Compression time (s, log scale)")
        ax.set_ylabel("Size ratio (% of original, lower is better)")
        ax.set_title(f"Size vs. compression time — {DATASET_LABEL[ds]}")
        ax.grid(True, which="both", ls=":", alpha=0.4)
        fig.tight_layout()
        fig.savefig(FIGS / f"pareto_{ds}.png", dpi=150)
        plt.close(fig)
        print(f"wrote paper/figures/pareto_{ds}.png")


def write_paper_section(rows: list[dict]) -> None:
    """A compact results section for the paper: full-corpus + text rankings,
    per-category winners, and the attempted-formats table. Injected into
    paper.md at build time (replacing the RESULTS_TABLES marker)."""
    parts = []
    for ds in ("full", "text"):
        t = dataset_table(rows, ds)
        if t:
            parts.append(t)

    # Per-category winner summary
    wins = ["### Best format per content category", "",
            "| Category | Smallest format | Ratio | Practical winner (mainstream) |",
            "|---|---|---:|---|"]
    mainstream = {"zip", "sevenzip", "tar-zst", "tar-gz", "rar5", "tar-xz"}
    for ds in corpus.DATASETS:
        sub = sorted([r for r in ok_rows(rows) if r["dataset"] == ds],
                     key=lambda r: r["ratio_pct"])
        if not sub:
            continue
        best = sub[0]
        prac = next((r for r in sub if r["id"] in mainstream), best)
        wins.append(f"| {DATASET_LABEL[ds]} | {best['name']} ({best['level']}) | "
                    f"{best['ratio_pct']:.2f}% | {prac['name']} — {prac['ratio_pct']:.2f}% |")
    wins.append("")
    parts.append("\n".join(wins))

    at = attempted_table(rows)
    if at:
        parts.append(at)
    (REPO / "results" / "tables" / "paper_results.md").write_text("\n\n".join(parts))


def main() -> int:
    rows = load_all()
    if not rows:
        print("no results yet in results/raw/")
        return 1
    write_csv(rows)
    write_markdown(rows)
    write_paper_section(rows)
    write_figures(rows)
    ok = sum(1 for r in rows if r["status"] == "ok")
    print(f"{len(rows)} run-units ({ok} ok) -> results/tables/, paper/figures/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
